export const  NEWUSER_REQUEST = "NEWUSER_REQUEST";
export const  NEWUSER_SUCCESS = "NEWUSER_SUCCESS";
export const  NEWUSER_FAIL = "NEWUSER_FAIL";
export const  NEWUSER_RESET = "NEWUSER_RESET";

export const  ALLUSERS_REQUEST = "ALLUSERS_REQUEST";
export const  ALLUSERS_SUCCESS = "ALLUSERS_SUCCESS";
export const  ALLUSERS_FAIL = "ALLUSERS_FAIL";


export const  ALLTASKS_REQUEST = "ALLTASKS_REQUEST";
export const  ALLTASKS_SUCCESS = "ALLTASKS_SUCCESS";
export const  ALLTASKS_FAIL = "ALLTASKS_FAIL";

