export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";


export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const LOADUSER_REQUEST = "LOADUSER_REQUEST";
export const LOADUSER_SUCCESS = "LOADUSER_SUCCESS";
export const LOADUSER_FAIL = "LOADUSER_FAIL";


export const NEWTASK_REQUEST = "NEWTASK_REQUEST";
export const NEWTASK_SUCCESS = "NEWTASK_SUCCESS";
export const NEWTASK_FAIL = "NEWTASK_FAIL";
export const NEWTASK_RESET = "NEWTASK_RESET";

export const MYTASKS_REQUEST = "MYTASKS_REQUEST";
export const MYTASKS_SUCCESS = "MYTASKS_SUCCESS";
export const MYTASKS_FAIL = "MYTASKS_FAIL";
export const MYTASKS_RESET = "MYTASKS_RESET";


